[package]
name = "four"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
advent.workspace = true
parse.workspace = true
strum = "0.26"
strum_macros = "0.26"
combine.workspace = true
